### PR TITLE
updated pre-commit hooks

### PR DESCRIPTION
**Pull request by ekageyama**
-Updated pre-commit hooks
-Added black profile to isort

### CODE REVIEW

**Comment by avantikalal** [comment]
> -Updated pre-commit hooks -Added black profile to isort

@ekageyama looks like tests are still failing?

**Comment by ekageyama** [comment]
this is very odd, the pre-commit passes locally, at least the black isort problem is solved

**Comment by ekageyama** [comment]
pre-commit.ci run

**Comment by avantikalal** [comment]
@ekageyama Looks like this all works now?

**Comment by ekageyama** [comment]
Yes, the checks from the hooks are all green 🤗

**Review by avantikalal — APPROVED** [review]

**Pull request merged**
